# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1013) do

  create_table "companies", :force => true do |t|
    t.column "name",    :string, :limit => 100, :default => "", :null => false
    t.column "address", :string, :limit => 200
    t.column "phone",   :string, :limit => 50
    t.column "fax",     :string, :limit => 50
    t.column "logo",    :string, :limit => 100
  end

  create_table "database_translation_fields", :force => true do |t|
    t.column "table", :string, :limit => 50, :default => "", :null => false
    t.column "field", :string, :limit => 50, :default => "", :null => false
  end

  create_table "database_translations", :force => true do |t|
    t.column "record_id", :integer,               :default => 0,  :null => false
    t.column "table",     :string,  :limit => 50, :default => "", :null => false
    t.column "field",     :string,  :limit => 50, :default => "", :null => false
    t.column "fr",        :text
    t.column "en",        :text
  end

  create_table "dimensions", :force => true do |t|
    t.column "serie_id", :integer,              :default => 0,   :null => false
    t.column "value",    :float,                :default => 0.0, :null => false
    t.column "type",     :string,  :limit => 6, :default => "",  :null => false
  end

  create_table "openings", :force => true do |t|
    t.column "name",               :string,  :limit => 50,  :default => "",    :null => false
    t.column "abbreviation",       :string,  :limit => 5,   :default => "",    :null => false
    t.column "openable",           :boolean,                :default => false, :null => false
    t.column "preview_image_name", :string,  :limit => 100
    t.column "glasses_quantity",   :integer,                :default => 1,     :null => false
  end

  create_table "openings_series", :id => false, :force => true do |t|
    t.column "opening_id", :integer, :default => 0, :null => false
    t.column "serie_id",   :integer, :default => 0, :null => false
  end

  create_table "options", :force => true do |t|
    t.column "description",             :string,  :limit => 50, :default => "",  :null => false
    t.column "comments",                :text
    t.column "pricing_method_id",       :integer,               :default => 0,   :null => false
    t.column "price",                   :float,                 :default => 0.0, :null => false
    t.column "minimum_quantity",        :float,                 :default => 0.0, :null => false
    t.column "options_minimum_unit_id", :integer,               :default => 1,   :null => false
  end

  create_table "options_minimum_units", :force => true do |t|
    t.column "description", :string, :limit => 50, :default => "", :null => false
    t.column "comments",    :text
  end

  create_table "options_quotation_lines", :id => false, :force => true do |t|
    t.column "option_id",         :integer, :default => 0, :null => false
    t.column "quotation_line_id", :integer, :default => 0, :null => false
  end

  create_table "options_series", :id => false, :force => true do |t|
    t.column "option_id", :integer, :default => 0, :null => false
    t.column "serie_id",  :integer, :default => 0, :null => false
  end

  create_table "permissions", :force => true do |t|
    t.column "role_id",    :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "pricing_methods", :force => true do |t|
    t.column "description", :string, :limit => 50, :default => "", :null => false
    t.column "comments",    :text
  end

  create_table "quotation_lines", :force => true do |t|
    t.column "quotation_id",     :integer, :default => 0,   :null => false
    t.column "serie_id",         :integer, :default => 0,   :null => false
    t.column "shape_id",         :integer, :default => 0,   :null => false
    t.column "width",            :float,   :default => 0.0, :null => false
    t.column "height",           :float,   :default => 0.0, :null => false
    t.column "quantity",         :integer, :default => 0,   :null => false
    t.column "price",            :float,   :default => 0.0, :null => false
    t.column "label",            :string
    t.column "standard_size_id", :integer
  end

  create_table "quotation_lines_openings", :force => true do |t|
    t.column "quotation_line_id", :integer, :default => 0, :null => false
    t.column "opening_id",        :integer, :default => 0, :null => false
    t.column "sort_order",        :integer, :default => 0, :null => false
  end

  create_table "quotations", :force => true do |t|
    t.column "description",      :string,  :limit => 50,  :default => "",    :null => false
    t.column "comments",         :text
    t.column "project_name",     :string,  :limit => 150
    t.column "customer_name",    :string,  :limit => 150
    t.column "customer_address", :string,  :limit => 200
    t.column "customer_phone",   :string,  :limit => 50
    t.column "customer_fax",     :string,  :limit => 50
    t.column "customer_email",   :string,  :limit => 50
    t.column "transport",        :float,                  :default => 0.0,   :null => false
    t.column "discount",         :float,                  :default => 0.0,   :null => false
    t.column "taxes",            :float,                  :default => 0.0,   :null => false
    t.column "notes",            :text
    t.column "ready_to_sign",    :boolean,                :default => false
    t.column "user_id",          :integer
  end

  create_table "roles", :force => true do |t|
    t.column "rolename", :string
  end

  create_table "section_dimensions", :force => true do |t|
    t.column "quotation_line_id", :integer,               :default => 0,   :null => false
    t.column "sort_order",        :integer,               :default => 0,   :null => false
    t.column "value",             :float,                 :default => 0.0, :null => false
    t.column "type",              :string,  :limit => 13, :default => "",  :null => false
  end

  create_table "serie_prices", :force => true do |t|
    t.column "width_id",   :integer, :default => 0,   :null => false
    t.column "height_id",  :integer, :default => 0,   :null => false
    t.column "opening_id", :integer, :default => 0,   :null => false
    t.column "price",      :float,   :default => 0.0, :null => false
  end

  create_table "series", :force => true do |t|
    t.column "name",             :string,  :limit => 50, :default => "", :null => false
    t.column "description",      :string,                :default => "", :null => false
    t.column "comments",         :text
    t.column "standard_size_id", :integer
    t.column "sheet_size_id",    :integer
    t.column "series_type",      :text
  end

  create_table "shapes", :force => true do |t|
    t.column "name",            :string,  :limit => 50, :default => "", :null => false
    t.column "sections_width",  :integer,               :default => 0,  :null => false
    t.column "sections_height", :integer,               :default => 0,  :null => false
    t.column "corners",         :integer,               :default => 4,  :null => false
  end

  create_table "sheet_sizes", :force => true do |t|
    t.column "description",      :string,  :limit => 256, :default => "",  :null => false
    t.column "minimum_width",    :integer,                :default => 0,   :null => false
    t.column "maximum_width",    :integer,                :default => 0,   :null => false
    t.column "minimum_height",   :integer,                :default => 0,   :null => false
    t.column "maximum_height",   :integer,                :default => 0,   :null => false
    t.column "price",            :float,                  :default => 0.0, :null => false
    t.column "sheet_product_id", :integer,                                 :null => false
  end

  create_table "standard_sizes", :force => true do |t|
    t.column "description",         :string,  :limit => 256, :default => "",  :null => false
    t.column "price",               :float,                  :default => 0.0, :null => false
    t.column "standard_product_id", :integer,                                 :null => false
  end

  create_table "translations", :force => true do |t|
    t.column "translation_key", :string, :limit => 100, :default => "", :null => false
    t.column "fr",              :text
    t.column "comments",        :text
    t.column "en",              :text
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "password_reset_code",       :string,   :limit => 40
    t.column "enabled",                   :boolean,                :default => true
    t.column "discount",                  :float,                  :default => 0.0,  :null => false
  end

end
