INSERT INTO translations (id, translation_key, fr, comments, en, es) VALUES (633, 'DISCLAIMER_TEXT', '1.4        L’ENTREPRENEUR déclare qu’il est en mesure de recevoir et de prendre possession des PRODUITS et qu''il a l''obligation et la responsabilité, exclusivement par l''entremise de son propre personnel, de voir promptement au déchargement des PRODUITS à l’adresse de livraison convenue. Entre autres,   L''ENTREPRENEUR déclare et s''engage à s''assurer, préalablement à la livraison, que le site de livraison peut accommoder un camion d''une longueur de 53 pieds et qu''il a obtenu, si nécessaire, les autorisations et/ou permis pour ce faire, notamment si la livraison entrave la voie publique.

       Alternativement, si le site de livraison ne peut accueillir un camion d''une longueur de 53 pieds, L''ENTREPRENEUR peut en aviser préalablement le vendeur au moment de la demande de soumission, laquelle sera ajustée en tenant compte de ce facteur dans le calcul des frais de transport qui seront alors augmentés par suite de la division des produits à être livrés dans des camions de moindre dimension. L''ENTREPRENEUR s’engage à assumer tous les frais supplémentaires ou pertes monétaires que pourrait encourir le VENDEUR, le cas échéant, si la livraison ne peut être effectuée à l’endroit ci-haut déterminé ou nécessite un temps supérieur à la normale, que ce soit en raison d''un manque de personnel affecté au déchargement des produits de L''ENTREPRENEUR et/ou en raison de la configuration des lieux, rendant l''opération du déchargement plus difficile.

        De plus, attendu que L''ENTREPRENEUR a la responsabilité de voir au déchargement du camion, toute perte ou bris, en dehors des limites du camion, qui pourrait survenir lors du déchargement devra être assumé exclusivement par L''ENTREPRENEUR.',
                                                                             '',
                                                                             '1.4 The CONTRACTOR acknowledges that it is able to receive and take possession of products and that it has the obligation and responsibility, exclusively through its own staff to promptly see to the unloading of the products at the agreed delivery address. Among other things, the Contractor represents and undertakes to ensure, prior to delivery, the delivery site can accommodate a 53-foot truck and will obtain, if necessary, authorizations and/or permits to do this, especially if delivery impedes the public highway.

                                                                             Alternatively, if the delivery site can NOT accommodate a truck 53 feet in length, the CONTRACTOR must inform the seller at the time of submission, which, as a result of the division of the products to be delivered in smaller trucks, will result in a recalculation of the transport costs. The Contractor assumes all additional expenses or monetary losses that might incur the seller, as appropriate, if delivery cannot be made to the specified location, above or requires more than normal, either due to a lack of staff assigned to the unloading of products by the CONTRACTOR and/or due to the configuration of the premises making it more difficult unloading operation.

                                                                             Moreover, whereas the CONTRACTOR is responsible for unloading the truck, any loss or breakage, assumed outside the bounds of the truck, which could occur when unloading shall be borne exclusively by the CONTRACTOR.',
                                                                             '1.4 El contratista declara que es capaz de recibir y tomar posesión de los productos y que tiene la obligación y la responsabilidad, exclusivamente a través de su propio personal para ver inmediatamente la descarga de los productos a la dirección de entrega convenida. Entre otras cosas, el contratista representa y se compromete a garantizar, antes de la entrega, el sitio de entrega puede acomodar a un camión de 53 pies y obtuvo, si es necesario, autorizaciones o permisos para hacer esto, especialmente si entrega impide la vía pública.

                                                                             Por otra parte, si el sitio de entrega puede acomodar a un camión de 53 pies de largo, el contratista puede informar al vendedor en el momento de la presentación, que será ajustada teniendo en cuenta este factor en el cálculo de los costos de transporte, que luego se incrementará como consecuencia de la división de los productos para ser entregados en camiones más pequeños. El contratista se compromete a asumir todos los gastos adicionales o pérdida monetaria que pudiera incurrir el vendedor, según corresponda, si no se puede hacer a la ubicación especificada arriba o requiere más de lo normal, debido a la falta de personal adscrito a la descarga de productos del contratista y/o debido a la configuración de los localeslo que es más difícil operación de descarga.

                                                                             Por otra parte, mientras que el contratista es responsable de la descarga del camión, cualquier pérdida o rotura, fuera de los límites del camión, que podría ocurrir cuando descarga correrán exclusivamente por el contratista.');
