# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', '3.1.12'

gem 'will_paginate', '>= 3.0.pre2'
gem 'paperclip', '=2.7.5'
gem 'formtastic'
gem 'validation_reflection'
gem 'mysql2','~> 0.3'
gem 'rmagick', '>= 2.13.2'
gem 'deep_cloneable', '~> 1.4.1'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'jquery-rails', '~> 2.1'
gem 'rails3-jquery-autocomplete'
gem 'jquery-migrate-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
#  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end
